### ISSUE TITLE
Cannot find name 'HeadersInit' in response.ts

### ISSUE THREAD

**Issue by jamesbohacek** [sholladay/pogo#23]
It seems that `headers` inside the `ResponseOptions` interface is using a type that is not defined in the file: `HeadersInit`. I fixed it locally by replacing it with `__domTypes.HeadersInit`, which is used by the `Headers` constructor:
```ts
const Headers: __domTypes.HeadersConstructor
new (init?: __domTypes.Headers | [string, string][] | Record<string, string> | undefined) => __domTypes.Headers
```

I also noticed that in the commit history this type was used at one point. Was there a purpose to replacing it? Otherwise I can create a PR with the fix.

**Comment by sholladay** [comment]
I think your Deno version is out of date. `__domTypes.HeadersInit` doesn't exist anymore as of Deno 0.41.0. I made the change in commit https://github.com/sholladay/pogo/pull/14/commits/4ca49964f734ee4fb037a4772fc21c33cb7d31b3 while working on PR #14, soon after updating the version of Deno used in CI.
