### ISSUE TITLE
README: React JSX Example Fails

### ISSUE THREAD

**Issue by chrisVillanueva** [sholladay/pogo#26]
Hi.

I tried to run your React example using code in the README.  `deno` complains about the code:

![pogo-errors](https://user-images.githubusercontent.com/1554280/81461210-2456e900-9178-11ea-87bb-cea6e46bcaad.png)

**Comment by sholladay** [comment]
Those errors are coming from Deno's `std` library, not Pogo itself. I'm guessing it's an incompatibility with your version of Deno. What do you get when you run `deno --vetsion`?

Pogo (and the version of `std` it depends on) is currently tested against Deno `0.41.0`. I know the release candidate for 1.0 was released recently - will update soon. PR to update the version of `std` is welcome.

**Comment by patlehmann1** [comment]
I can update to std version 0.50.0, however this was just pushed up an hour ago, your call. https://github.com/denoland/deno/blob/master/docs/runtime/stability.md

**Comment by chrisVillanueva** [comment]
> Those errors are coming from Deno's `std` library, not Pogo itself. I'm guessing it's an incompatibility with your version of Deno. What do you get when you run `deno --vetsion`?
> 
> Pogo (and the version of `std` it depends on) is currently tested against Deno `0.41.0`. I know the release candidate for 1.0 was released recently - will update soon. PR to update the version of `std` is welcome.

Thanks for the quick reply. Here is the information you requested:

deno 1.0.0-rc1
v8 8.2.308
typescript 3.8.3
