### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by sholladay** [sholladay/pogo#30]
Now that Pogo's APIs are stable and we're getting more users, I think it would be nice to add some "fit and finish" in the form of a logo.

Anyone have logo ideas or want to try making one?

Here's some inspiration from my favorite ideas:

 - [Kid on a pogo stick](http://www.howitworksdaily.com/wp-content/uploads/2013/08/78744762.jpg)
 - [Ox with a beard](https://www.travel4wildlife.com/wp-content/uploads/2015/05/musk-ox-female.jpg)
 - [Tucan bird](http://4.bp.blogspot.com/-tsGDGlr87iY/T7A0g_AGs_I/AAAAAAAACgI/PTUgmoFOGXQ/s1600/Toco+toucan+Ramphastos+toco.jpg)

The logo should be in a vector format, ideally Adobe Illustrator or SVG.

**Comment by Kharanshu31** [comment]
Can it be a picture from the web?

**Comment by buttercubz** [comment]
I think it could be a bear, when listening to pogo I imagine a bear. 
can I try to make a bear in pixel art

**Comment by sholladay** [comment]
That's funny, I've considered changing the name of the project a few times and Bear is an option I've thought about. Has some negative connotations, though, especially when applied to non-living things.

I originally chose Pogo because HTTP requests bouncing back and forth reminded me of a [pogo stick](https://en.wikipedia.org/wiki/Pogo_stick), which is a fun childhood memory for many people. I'm not in love with it, just the first thing that came to mind that was short and upbeat. I like the idea of a creature for a logo/mascot. Deno has a dinosaur, of course. Maybe some kind of bird? A spider would be appropriate (web), but some people find them creepy.

**Comment by buttercubz** [comment]
![pogo](https://image.freepik.com/vector-gratis/estilo-dibujos-animados-oso-polar-pixel_61878-528.jpg)

It would be something similar, of course done by someone who knows graphic design

**Comment by PazzaVlad** [comment]
Also think that a bear would be a good mascot)

**Comment by buttercubz** [comment]
yes, do you know someone who knows how to design?  @PazzaVlad

**Comment by mlovelook** [comment]
Hi! 
I'm a designer and I'm looking for OS projects to collaborate. You guys are needing some help? I can give a try at the logo if you guys want.

**Comment by sholladay** [comment]
@mlovelook that would be wonderful. You can find me on Deno's Discord if you want to chat.

Ideally, I'd like to find a collaborator who could take the lead on non-code related things: documentation, logos, marketing, website design, etc. Let me know if that interests you.

**Comment by mlovelook** [comment]
Yeah! I can start with the logo, and after we can see if I have time to help with anything else. I don't know if I can take so many responsibilities at the time, but seems good.

**Comment by rahulmaheshwari1111** [comment]
Is the logo part done?

**Comment by sholladay** [comment]
@rahulmaheshwari1111 not yet. I would love for someone to contribute a logo. Please do if you can! I just updated the [original issue](https://github.com/sholladay/pogo/issues/30#issue-624030967) with some links for inspiration.

**Comment by rahulmaheshwari1111** [comment]
Yeah sure !!

**Comment by vivekchauhan12000** [comment]
I have some designs and like to share them with all and would great if used in

**Comment by vivekchauhan12000** [comment]
![logoooo](https://user-images.githubusercontent.com/49834398/111903521-b1d9b980-8a68-11eb-80a4-1968e211fe7f.JPG)

here are some of them

**Comment by sholladay** [comment]
Looks cool. The combination of smooth curves and sharp angles is interesting. I like the powerful and confident vibe, but it also looks a bit scary.

**Comment by vivekchauhan12000** [comment]
how is this idea pogo stick with rocket instead of a kid it will send a straight message of speed and unreached height

**Comment by Tnifey** [comment]
Why not to make a kid dinosaur on Pogo? 
![image](https://user-images.githubusercontent.com/8442019/114787675-7937b200-9d80-11eb-9bb0-076a5650356b.png)

**Comment by sholladay** [comment]
Ooh, I like `it2`, @Tnifey! That dino looks like it's having fun while also escaping the rain, which aligns well with the goals of the project.

**Comment by Tnifey** [comment]
@sholladay I really appreciate that you liked that. I have made some refinements, but I think it was better with raw `iteration2` :P

![image](https://user-images.githubusercontent.com/8442019/115094495-13812c80-9f1e-11eb-9f77-ec18b921ce39.png)

But what next? How to proceed with legals on open-source projects :P Is it alright to send you .svg without any agreements on both side? 

Also, I have made some drawing with space theme, like @vivekchauhan12000 have posted, I have taken inspiration from Superman pose and Postman logo.

![image](https://user-images.githubusercontent.com/8442019/115094184-f7c95680-9f1c-11eb-85d8-0506ad0a079d.png)
![image](https://user-images.githubusercontent.com/8442019/115094313-5ee70b00-9f1d-11eb-9f19-435a551bf49f.png)
![image](https://user-images.githubusercontent.com/8442019/115094469-e896d880-9f1d-11eb-8ec5-d4e89bb38de3.png)

**Comment by sholladay** [comment]
I just asked a few friends and the original iteration 2 was a clear favorite, followed by iteration 1. There may be some cases where a perfectly circular icon would be useful, so it would be nice to have iteration 2 for the main logo and then also have a variant where the dino is completely inside the circle, to be used as an avatar or favicon, etc.

The astronaut, to me, looks a bit too mysterious, maybe because there is no face. Kind of reminds me of the ["always has been"](https://knowyourmeme.com/memes/wait-its-all-ohio-always-has-been) memes. Although, I do like the fist bumping duo, that one looks much more friendly.

Regarding intellectual property, I am not a lawyer but the existing [MPL-2.0](https://www.mozilla.org/en-US/MPL/2.0/) license should be sufficient to cover this type of contribution, so long as you're comfortable with it.

Some useful resources:
 - https://www.mozilla.org/en-US/MPL/2.0/FAQ/#non-software-works
 - https://docs.github.com/en/github/site-policy/github-terms-of-service#6-contributions-under-repository-license
 - https://www.finnegan.com/en/insights/articles/what-you-should-know-about-contributor-license-agreements-in-open-source-projects.html
 - https://opensource.guide/legal/

I don't require a CLA. And as for the copyright, we can change the notice to say "and project contributors", if you'd like.

**Comment by Tnifey** [comment]
@sholladay I have made repository with Mozilla Public License 2.0, with 3 variants of `iteration 2`.
It includes png, svg and adobe xd project file.

https://github.com/Tnifey/pogo-logo-design

Keep writing good code and have nice day :P

**Comment by sholladay** [comment]
@Tnifey's dino is now the official logo. Take a look at the [README](https://github.com/sholladay/pogo/blob/master/README.md), I think it looks great! 😀

Credit is given in the [media](https://github.com/sholladay/pogo/tree/master/media) folder. Send a PR if you want it anywhere else, too.

Many thanks to everyone who contributed proposals. There will be more graphics needed in the future for the website, plugins, etc.

I may have to go make some stickers now... 😉
