### ISSUE TITLE
CSSType 302 has no location

### ISSUE THREAD

**Issue by khrome83** [sholladay/pogo#49]
Pika is no longer returning this package. If you request it, it's a 302 without a location. This causes Rust to panic.

curl the file, and you get a message that you should use this - https://cdn.skypack.dev/csstype

```
thread 'main' panicked at 'url redirection should provide 'location' header', cli/http_util.rs:141:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I can not tell what dependency in Pogo that is requesting this. But I have isolated it as the use of pogo that has caused this.

`https://cdn.pika.dev/csstype/dist=es2019,mode=types/index.d.ts`

You can see this by running a test with -r to redownload.

The snowpack url does work though. Even though I am not using this feature in pogo, it impacting me. Maybe some of them react support could be a plugin in the future. I have a feeling this may be from the inclusion of react/jsx with pogo.

**Comment by sholladay** [comment]
Fixed in https://github.com/sholladay/pogo/commit/64ef11371480e32eb8323ddbe3ad46781d1d75ea.

I decided to migrate back to the JSPM CDN for now, because Pika is too unstable.
