### ISSUE TITLE
Consider using Pagic to build the website?

### ISSUE THREAD

**Issue by xcatliu** [sholladay/pogo#51]
[Pagic](https://pagic.org) is a static site generator powered by Deno + React

Here are some demos:

- [pagic.org](https://pagic.org)
- [Deno X ranking](https://yoshixmk.github.io/deno-x-ranking/)
- [TypeScript 入门教程](https://ts.xcatliu.com/)

If it is possible to use pagic to build the website, I would like to create the pull-request

**Comment by sholladay** [comment]
Looks nice, I like it! Great name, too.

That said, the Pogo website will be built with Pogo itself or a generator / framework built on top of Pogo. It needs to be "pure" in that sense or people won't take it as seriously. I want to demonstrate that Pogo is a real, useful framework capable of being used in production projects. There are a few hurdles to overcome before I declare that to be fully solved, but building a website would go a long way towards proving it.

If there's something that would help you adopt Pogo, feel free to chime in here on the issue tracker.
