### ISSUE TITLE
[Question] Check if handler already exists for route

### ISSUE THREAD

**Issue by KaKi87** [sholladay/pogo#65]
Hello,

Is it possible to programmatically check if an handler already exists for a specific route ?

Thanks

**Comment by sholladay** [comment]
You can inspect the existing routes in the routing table by looking at `server.router`. In particular, the router has a [`routes`](https://github.com/sholladay/pogo#routerroutes) property and a [`lookup()`](https://github.com/sholladay/pogo#routerlookupmethod-path) method.

So, for example, you could do something like this:

```js
const route = server.router.lookup('GET', '/');
const hasHandler = Boolean(route?.handler);
```

Admittedly, the documentation for those APIs is a bit sparse. PRs welcome to expand upon it.

**Comment by KaKi87** [comment]
[I actually needed `server.router.routes.list`](https://git.kaki87.net/cv.vg/api/commit/aa4027c1713d8c7871e9e5bcb729df40e0a36bc1), thanks !

**Comment by sholladay** [comment]
Very cool, thanks for sharing your usage of it.

By the way, I'm working on #62 and those changes will likely fix your bug #66 at the same time. Let me know if you have any other suggestions, as I'm planning a new release soon.

**Comment by KaKi87** [comment]
Alright !

Well, I implemented everything I needed to automate in this [`route.js`](https://git.kaki87.net/cv.vg/api/src/branch/dev/lib/route.js) file :
- CORS (#31)
- JSON body parsing (#19 / #41)
- params & body validation (#67)
- error catching
(I didn't looked for nor created an issue for this, basically you could expose an `error` event that could be globally listened to, like `server.on('error', callback)`).

One last thing I'm missing is Sentry (or alternative) integration but that's up to them (getsentry/sentry-javascript#3009).

**Comment by KaKi87** [comment]
Oh and I needed BasicAuth too.
