### ISSUE TITLE
Binding to Different IP?

### ISSUE THREAD

**Issue by fangmarks** [sholladay/pogo#70]
Hey so I've tried binding to 0.0.0.0, but it seems like that doesn't work, and when looking through the code, I've noticed that in [lib/server.ts#L47](https://github.com/sholladay/pogo/blob/091d2287b92470b316e9e81ee81ed21732c01aab/lib/server.ts#L47), only localhost is set, but the given input by a user for `hostname` is ignored

**Comment by himbolion** [comment]
It was really late for me, Ignore this. it does  actually work lol
